# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
  - name: SpacyNLP
    model: en_core_web_md
    case_sensitive: False
  - name: SpacyTokenizer
  - name: sentiment.SentimentAnalyzer
  - name: SpacyFeaturizer
    "pooling": "mean"
  - name: RegexFeaturizer
    case_sensitive: False
    # use match word boundaries for lookup table
    "use_word_boundaries": True
  - name: DIETClassifier
    entity_recognition: False
    model_confidence: linear_norm
    constrain_similarities: True
    epochs: 300
  - name: CRFEntityExtractor
    features:
      [
        ["low", "title", "upper", "prefix2", "suffix2"],
        [
          "bias",
          "low",
          "prefix5",
          "prefix2",
          "suffix5",
          "suffix3",
          "suffix2",
          "upper",
          "title",
          "digit",
          "pattern",
        ],
        ["low", "title", "upper", "prefix2", "suffix2"],
      ]
  - name: EntitySynonymMapper
  - name: ResponseSelector
    retrieval_intent: out_of_scope
    scale_loss: false
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.7
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 10
    model_confidence: linear_norm
    constrain_similarities: True
    epochs: 20
    batch_size:
      - 32
      - 64
  - max_history: 6
    name: AugmentedMemoizationPolicy
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: True
